### ISSUE TITLE
Attempt to index local 'action'(a number value)

### ISSUE THREAD

**Issue by sharpchen** [rachartier/tiny-code-action.nvim#1]
### Setup

- install omnisharp using mason, requires `Hoffs/omnisharp-extended-lsp.nvim`(I don't think it's the problem, but I just keep it here)
```lua
require('mason-lspconfig').setup({
  handlers = {
    function(server_name)
      require('lspconfig')[server_name].setup({})
    end,
    omnisharp = function()
      require('lspconfig').omnisharp.setup({
        handlers = {
          ['textDocument/definition'] = require('omnisharp_extended').definition_handler,
          ['textDocument/typeDefinition'] = require('omnisharp_extended').type_definition_handler,
          ['textDocument/references'] = require('omnisharp_extended').references_handler,
          ['textDocument/implementation'] = require('omnisharp_extended').implementation_handler,
        },
      })
    end,
})

```

- lazy config
```lua
return {
  'rachartier/tiny-code-action.nvim',
  dependencies = {
    { 'nvim-lua/plenary.nvim' },
    { 'nvim-telescope/telescope.nvim' },
  },
  event = 'LspAttach',
  config = function()
    require('tiny-code-action').setup()
    vim.keymap.set('n', '<leader>ca', function()
      require('tiny-code-action').code_action()
    end, { noremap = true, silent = true })
  end,
}

```

## Test

Open any csharp project, type `<leader>ca` where code action exists. It throws the following error.

![image](https://github.com/user-attachments/assets/8b12afdd-aa7e-46b9-9dd9-04047050a28b)

**Comment by rachartier** [comment]
Hello!

Oh that's strange... I'm using omnisharp with omnisharp-extended-lsp.nvim for my testing.
What is your language server? `omnisharp` or `omnisharp-roslyn` ?

**Comment by Alpensin** [comment]
same error with ruff and ruff_lsp code actions

```
Error executing vim.schedule lua callback: ...zy/tiny-code-action.nvim/lua/tiny-code-action/action.lua:68: attempt to index local 'action' (a number value)
stack traceback:
        ...zy/tiny-code-action.nvim/lua/tiny-code-action/action.lua:68: in function 'preview_action_callback'
        ...ny-code-action.nvim/lua/tiny-code-action/backend/vim.lua:24: in function 'callback'
        ...zy/tiny-code-action.nvim/lua/tiny-code-action/action.lua:15: in function 'handler'
        .../neovim/0.10.0/share/nvim/runtime/lua/vim/lsp/client.lua:685: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
Works fine with `gopls`

**Comment by rachartier** [comment]
Yep that's my bad, really sorry.

It should be fixed now !

**Comment by nmiguel** [comment]
I'm afraid this is still occurring as of [`7b3ae2f`](https://github.com/rachartier/tiny-code-action.nvim/commit/7b3ae2f39d83ed6de22beacc1af57ad0f699f0ec) . Error was with gopls LSP. It should be noted that the action itself would fail.

Error executing vim.schedule lua callback: ...zy/tiny-code-action.nvim/lua/tiny-code-action/action.lua:4: attempt to index local 'action' (a nil value)
stack traceback:
        ...zy/tiny-code-action.nvim/lua/tiny-code-action/action.lua:4: in function 'apply'
        ...lazy/tiny-code-action.nvim/lua/tiny-code-action/init.lua:181: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:685: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

**Comment by rachartier** [comment]
I've added a check to not execute the action if it would fail.
Can you tell me please what LSP are you using ? To debug it further.

**Comment by nmiguel** [comment]
I'm using gopls, the action in question is with this snippet:

`log.Fatal(err)`
Which should inline call to fatal (but fails)

**Comment by rachartier** [comment]
Thank you a lot.

I did reproduce the error, and it should now be fixed (I hope this time!)

**Comment by nmiguel** [comment]
Confirmed, thanks
